version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=ruben
      - MARIADB_DATABASE=gametracker_db
  myapp:
    image: docker.io/bitnami/laravel:8
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=ruben
      - DB_DATABASE=gametracker_db
    volumes:
      - './gametracker:/app'
    depends_on:
      - mariadb
