services:
  mariadb:
    image: mariadb:11.2
    ports:
      - '3306:3306'
    environment:
      # MARIADB_ALLOW_EMPTY_ROOT_PASSWORD is recommended only for development.
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=ruben
      - MARIADB_PASSWORD=ruben
      - MARIADB_DATABASE=gametracker
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=ruben
      - DB_PASSWORD=ruben
      - DB_DATABASE=gametracker
    volumes:
      - gametracker_data:/app
    depends_on:
      - mariadb
    #command: bash -c "composer install"

volumes:
  gametracker_data: # Docker creará este volumen automáticamente
